# Generated by Django 2.0.7 on 2018-07-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0004_branchuser_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
