# Generated by Django 2.0.7 on 2018-07-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0005_auto_20180723_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
    ]
