# Generated by Django 2.0.7 on 2018-07-24 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashcodrf', '0008_routeplan_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('location_lat', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('Account', 'Account'), ('Loan', 'Loan')], default='Account', max_length=6)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashcodrf.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
