# Generated by Django 2.0.7 on 2018-07-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0009_routeplanlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeplanlog',
            name='location',
        ),
        migrations.AddField(
            model_name='routeplanlog',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashcodrf.Branch'),
            preserve_default=False,
        ),
    ]
