# Generated by Django 2.0.7 on 2018-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0010_auto_20180724_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeplanlog',
            name='action',
            field=models.CharField(default='Account', max_length=15),
        ),
    ]
