# Generated by Django 2.0.7 on 2018-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0011_auto_20180724_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplanlog',
            name='location_lon',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
