# Generated by Django 2.0.7 on 2018-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0012_routeplanlog_location_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeplanlog',
            name='location_lon',
            field=models.CharField(max_length=128),
        ),
    ]
