# Generated by Django 2.0.7 on 2018-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0014_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
    ]
