# Generated by Django 2.0.7 on 2018-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0015_auto_20180724_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.IntegerField(),
        ),
    ]
