# Generated by Django 2.0.7 on 2018-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0016_auto_20180724_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
    ]
