# Generated by Django 2.0.7 on 2018-07-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0018_auto_20180724_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplanlog',
            name='summary',
            field=models.TextField(default='Client visit'),
        ),
    ]
