# Generated by Django 2.0.7 on 2018-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcodrf', '0019_routeplanlog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.IntegerField(unique=True),
        ),
    ]
